-- Create Database
CREATE DATABASE MovimentosManuais;
GO

USE MovimentosManuais;
GO

-- Create Table PRODUTO
CREATE TABLE PRODUTO (
    COD_PRODUTO CHAR(4) NOT NULL,
    DES_PRODUTO VARCHAR(30) NULL,
    STA_STATUS CHAR(1) NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (COD_PRODUTO),
    CONSTRAINT CHK_PRODUTO_STATUS CHECK (STA_STATUS IN ('A', 'I'))
);
GO

-- Create Table PRODUTO_COSIF
CREATE TABLE PRODUTO_COSIF (
    COD_PRODUTO CHAR(4) NOT NULL,
    COD_COSIF VARCHAR(11) NOT NULL,
    COD_CLASSIFICACAO CHAR(6) NULL,
    STA_STATUS CHAR(1) NULL,
    CONSTRAINT PK_PRODUTO_COSIF PRIMARY KEY (COD_PRODUTO, COD_COSIF),
    CONSTRAINT FK_PRODUTO_COSIF_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
    CONSTRAINT CHK_PRODUTO_COSIF_STATUS CHECK (STA_STATUS IN ('A', 'I'))
);
GO

-- Create Table MOVIMENTO_MANUAL
CREATE TABLE MOVIMENTO_MANUAL (
    DAT_MES INT NOT NULL,
    DAT_ANO INT NOT NULL,
    NUM_LANCAMENTO BIGINT NOT NULL,
    COD_PRODUTO CHAR(4) NOT NULL,
    COD_COSIF VARCHAR(11) NOT NULL,
    VAL_VALOR DECIMAL(18,2) NOT NULL,
    DES_DESCRICAO VARCHAR(50) NOT NULL,
    DAT_MOVIMENTO SMALLDATETIME NOT NULL,
    COD_USUARIO VARCHAR(15) NOT NULL,
    CONSTRAINT PK_MOVIMENTO_MANUAL PRIMARY KEY (DAT_MES, DAT_ANO, NUM_LANCAMENTO),
    CONSTRAINT FK_MOVIMENTO_MANUAL_PRODUTO_COSIF FOREIGN KEY (COD_PRODUTO, COD_COSIF) REFERENCES PRODUTO_COSIF(COD_PRODUTO, COD_COSIF)
);
GO

-- Create Stored Procedure for Querying Movements
USE [MovimentosManuais]
GO
/****** Object:  StoredProcedure [dbo].[spListaMovimentoManual]    Script Date: 4/30/2025 4:48:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
 ALTER   PROCEDURE [dbo].[spListaMovimentoManual] AS
     SELECT
         [MOVIMENTO_MANUAL].[DAT_MES] AS Mes,
         [MOVIMENTO_MANUAL].[DAT_ANO] AS Ano,
         [PRODUTO].[COD_PRODUTO] AS CodigoProduto,
         [PRODUTO].[DES_PRODUTO] AS DescricaoProduto,
         [MOVIMENTO_MANUAL].[NUM_LANCAMENTO] AS NumeroLancamento,
         [MOVIMENTO_MANUAL].[DES_DESCRICAO] AS Descricao,
         [MOVIMENTO_MANUAL].[VAL_VALOR] AS Valor
     FROM 
         [MOVIMENTO_MANUAL]
         INNER JOIN [PRODUTO]
             ON [MOVIMENTO_MANUAL].[COD_PRODUTO] = [PRODUTO].[COD_PRODUTO]
     ORDER BY 
         [MOVIMENTO_MANUAL].[DAT_MES], 
         [MOVIMENTO_MANUAL].[DAT_ANO], 
         [MOVIMENTO_MANUAL].[NUM_LANCAMENTO];

GO

-- Insert Sample Data
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) VALUES
('P001', 'Produto A', 'A'),
('P002', 'Produto B', 'A');
GO

INSERT INTO PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) VALUES
('P001', 'COSIF001', 'NORM01', 'A'),
('P002', 'COSIF002', 'NORM02', 'A');
GO

INSERT INTO MOVIMENTO_MANUAL (DAT_MES, DAT_ANO, NUM_LANCAMENTO, COD_PRODUTO, COD_COSIF, VAL_VALOR, DES_DESCRICAO, DAT_MOVIMENTO, COD_USUARIO) VALUES
(1, 2023, 1, 'P001', 'COSIF001', 1000.50, 'Movimento Inicial', '2023-01-01 10:00:00', 'enclidato'),
(1, 2023, 2, 'P002', 'COSIF002', 2000.75, 'Movimento Secundário', '2023-01-02 12:00:00', 'enclidato');
GO